Repository bcgov/common-object-management-service, pull requests merged in 2022-07, with the labels that each got.

#48 Bugfix: Offer decoupled configmap generation in Helm chart
  charts/coms/Chart.yaml
  charts/coms/templates/NOTES.txt
  charts/coms/templates/configmap.yaml
  charts/coms/templates/deploymentconfig.yaml
  charts/coms/templates/hpa.yaml
  charts/coms/templates/route.yaml
  charts/coms/templates/secret.yaml
  charts/coms/templates/service.yaml
  charts/coms/templates/serviceaccount.yaml
  charts/coms/values.yaml
Labels: bug

#49 Bugfix broken image
  app/Dockerfile
  app/package-lock.json
  app/package.json
  charts/coms/Chart.yaml
Labels: bug

#51 CI/CD: Implement Github Actions Helm Chart deployment flow
  .dockerignore
  .github/actions/build-push-container/action.yaml
  .github/actions/deploy-to-environment/action.yaml
  .github/actions/push-to-registry/action.yaml
  .github/environments/values.dev.yaml
  .github/environments/values.prod.yaml
  .github/environments/values.test.yaml
  .github/workflows/docker-image.yaml
  .github/workflows/on-push.yaml
  Dockerfile
  README.md
  charts/coms/Chart.yaml
  charts/coms/templates/configmap.yaml
  charts/coms/values.yaml
Labels: bug, enhancement

#53 Helm: Force basicAuth secrets to always be release scoped
  charts/coms/Chart.yaml
  charts/coms/templates/configmap.yaml
  charts/coms/templates/secret.yaml
Labels: bug

#50 Object tagging
  app/src/components/constants.js
  app/src/controllers/object.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1/object.js
  app/src/services/storage.js
  app/tests/unit/controllers/object.spec.js
  app/tests/unit/services/storage.spec.js
Labels: enhancement

#55 CI/CD: Implement Github Actions Pull Request flow support
  .github/CODEOWNERS
  .github/actions/build-push-container/action.yaml
  .github/actions/deploy-to-environment/action.yaml
  .github/actions/push-to-registry/action.yaml
  .github/environments/values.pr.yaml
  .github/workflows/charts-release.yaml
  .github/workflows/codeql-analysis.yaml
  .github/workflows/on-pr-closed.yaml
  .github/workflows/on-pr-opened.yaml
  .github/workflows/on-push.yaml
  .github/workflows/unit-tests.yaml
  README.md
  charts/coms/Chart.yaml
  charts/coms/templates/deploymentconfig.yaml
  openshift/README.md
  openshift/app.bc.yaml
  openshift/app.dc.yaml
Labels: bug, enhancement

#52 Metadata and Tag service layer, object controller refactor
  app/src/components/utils.js
  app/src/controllers/object.js
  app/src/db/migrations/20220627000000_002-metadata-tags.js
  app/src/db/models/utils.js
  app/src/docs/v1.api-spec.yaml
  app/src/services/index.js
  app/src/services/metadata.js
  app/src/services/storage.js
  app/src/services/tag.js
  app/src/services/version.js
  app/src/validators/object.js
  app/tests/unit/controllers/object.spec.js
  app/tests/unit/services/storage.spec.js
  app/tests/unit/validators/object.spec.js
Labels: enhancement

#58 Consolidate build-push-container action to multi-registry deploy
  .github/actions/build-push-container/action.yaml
  .github/actions/push-to-registry/action.yaml
  .github/workflows/on-pr-opened.yaml
  .github/workflows/on-push.yaml
Labels: bug
