Repository bcgov/common-object-management-service, pull requests merged in 2022-04, with the labels that each got.

#26 Extend identity management and user discovery support
  app/config/custom-environment-variables.json
  app/src/components/utils.js
  app/src/controllers/object.js
  app/src/controllers/permission.js
  app/src/controllers/user.js
  app/src/db/migrations/20220130133615_000-init.js
  app/src/db/models/tables/identityProvider.js
  app/src/db/models/tables/objectModel.js
  app/src/db/models/tables/objectPermission.js
  app/src/db/models/tables/permission.js
  app/src/db/models/tables/user.js
  app/src/db/models/utils.js
  app/src/middleware/authorization.js
  app/src/routes/v1/permission.js
  app/src/routes/v1/user.js
  app/src/services/object.js
  app/src/services/permission.js
  app/src/services/user.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/controllers/permission.spec.js
  app/tests/unit/middleware/authorization.spec.js
  app/tests/unit/services/user.spec.js
Labels: bug, documentation, enhancement

#28 Upgrade listObjects to searchObjects endpoint
  app/package-lock.json
  app/package.json
  app/src/controllers/object.js
  app/src/controllers/permission.js
  app/src/controllers/user.js
  app/src/db/models/tables/objectModel.js
  app/src/routes/v1/object.js
  app/src/services/object.js
  app/src/services/permission.js
  app/src/services/storage.js
  app/src/services/user.js
  app/tests/unit/services/storage.spec.js
  app/tests/unit/services/user.spec.js
Labels: bug, documentation, enhancement, dependencies

#29 Endpoint security bugfixes and audit table optimization
  app/app.js
  app/src/db/migrations/20220130133615_000-init.js
  app/src/middleware/featureToggle.js
  app/src/routes/v1/object.js
  app/src/routes/v1/user.js
  app/tests/unit/middleware/featureToggle.spec.js
Labels: bug

#31 Bugfix Keycloak config crash in non-OIDC Auth modes
  app/app.js
  app/src/db/dataConnection.js
  app/src/middleware/authentication.js
Labels: bug

#32 Update OpenAPI spec for MVP 0.1.0 release
  LICENSE
  app/app.js
  app/src/components/utils.js
  app/src/controllers/object.js
  app/src/controllers/user.js
  app/src/db/models/utils.js
  app/src/docs/docs.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1/docs.js
  app/src/routes/v1/index.js
  app/src/routes/v1/object.js
  app/src/routes/v1/permission.js
  app/src/routes/v1/user.js
  app/src/services/object.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/controllers/permission.spec.js
  app/tests/unit/middleware/authentication.spec.js
  app/tests/unit/middleware/authorization.spec.js
  app/tests/unit/middleware/featureToggle.spec.js
  app/tests/unit/routes/v1.spec.js
  app/tests/unit/routes/v1/docs.spec.js
  app/tests/unit/routes/v1/object.spec.js
  app/tests/unit/services/storage.spec.js
Labels: bug, documentation, enhancement

#30 Readme updates for app configuration and env variables
  README.md
  app/README.md
Labels: documentation

#33 General updates on readme documentation
  README.md
  SECURITY.md
  _config.yml
  app/README.md
  app/config/custom-environment-variables.json
  app/src/docs/v1.api-spec.yaml
  openshift/README.md
Labels: documentation

#34 Fix app lifecycle badge to maturing
  README.md
  app/README.md
Labels: documentation

#35 Bugfix .git directory discovery
  app/src/components/utils.js
  openshift/app.bc.yaml
Labels: bug
