Repository bcgov/common-object-management-service, pull requests merged in 2022-08, with the labels that each got.

#59 Bump minimum supported version docs
  SECURITY.md
Labels: documentation

#57 Generate internal uuid for COMS user, getCurrentUserId function
  app/src/controllers/object.js
  app/src/controllers/permission.js
  app/src/middleware/authorization.js
  app/src/services/user.js
  app/tests/common/dbHelper.js
  app/tests/unit/controllers/object.spec.js
  app/tests/unit/controllers/permission.spec.js
  app/tests/unit/middleware/authorization.spec.js
  app/tests/unit/services/user.spec.js
Labels: enhancement

#60 Add explicit wait step to deployment
  .github/actions/deploy-to-environment/action.yaml
Labels: bug

#61 Prevent workflows from running in parallel
  .github/workflows/on-pr-closed.yaml
  .github/workflows/on-pr-opened.yaml
  .github/workflows/on-push.yaml
Labels: bug

#63 Implement metadata search functionality
  app/app.js
  app/src/controllers/object.js
  app/src/db/models/tables/objectModel.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1/object.js
  app/src/services/object.js
Labels: documentation, enhancement

#65 Implement Tagging/TagSet Search Functionality
  app/src/components/utils.js
  app/src/controllers/object.js
  app/src/db/models/tables/objectModel.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1/object.js
  app/src/services/metadata.js
  app/src/services/object.js
  app/src/services/storage.js
  app/src/services/tag.js
  app/src/services/version.js
  app/src/validators/object.js
  app/tests/unit/controllers/object.spec.js
  app/tests/unit/validators/object.spec.js
Labels: bug, documentation, enhancement

#66 Refactor general CORS behavior
  app/app.js
  app/src/controllers/object.js
  app/src/routes/v1/object.js
  app/tests/unit/controllers/object.spec.js
Labels: bug, enhancement

#68 Allow signedUrl to be emitted as content
  app/src/components/constants.js
  app/src/controllers/object.js
  app/src/docs/v1.api-spec.yaml
  app/src/validators/common.js
  app/src/validators/object.js
  app/src/validators/permission.js
  app/tests/unit/validators/common.spec.js
  app/tests/unit/validators/object.spec.js
  app/tests/unit/validators/permission.spec.js
Labels: bug, documentation, enhancement
