Repository bcgov/common-object-management-service, pull requests merged in 2022-12, with the labels that each got.

#98 Feat/2927 bucket object permissions
  app/src/components/utils.js
  app/src/controllers/bucketPermission.js
  app/src/controllers/objectPermission.js
  app/src/services/bucketPermission.js
  app/src/validators/bucketPermission.js
Labels: enhancement

#95 Expose GET /object and /bucket endpoints
  app/src/components/utils.js
  app/src/controllers/bucket.js
  app/src/controllers/object.js
  app/src/controllers/objectPermission.js
  app/src/docs/v1.api-spec.yaml
  app/src/validators/bucket.js
  app/src/validators/object.js
  app/tests/unit/controllers/objectPermission.spec.js
Labels: enhancement

#99 Refactor getPath utility and fix public access in middleware
  app/src/components/utils.js
  app/src/controllers/object.js
  app/src/middleware/authorization.js
  app/src/routes/v1/object.js
  app/src/services/object.js
  app/src/services/storage.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/services/storage.spec.js
Labels: bug, enhancement

#100 Refactor upload bucket contextual behavior
  app/package-lock.json
  app/package.json
  app/src/components/errorToProblem.js
  app/src/components/utils.js
  app/src/controllers/bucket.js
  app/src/controllers/metadata.js
  app/src/controllers/object.js
  app/src/services/storage.js
  app/src/validators/bucket.js
  app/src/validators/object.js
  app/tests/unit/components/errorToProblem.spec.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/controllers/metadata.spec.js
  app/tests/unit/controllers/object.spec.js
  app/tests/unit/services/storage.spec.js
  app/tests/unit/services/user.spec.js
  app/tests/unit/validators/metadata.spec.js
  app/tests/unit/validators/object.spec.js
  charts/coms/Chart.yaml
Labels: bug, enhancement

#101 General GA Pipeline maintenance
  .github/actions/build-push-container/action.yaml
  .github/workflows/codeql-analysis.yaml
  .github/workflows/unit-tests.yaml
Labels: bug

#104 Updating (swagger) api spec to comply with current endpoint(s) implementation
  app/src/docs/v1.api-spec.yaml
Labels: documentation
