Repository bcgov/common-object-management-service, pull requests merged in 2022-06, with the labels that each got.

#38 Schema validation middleware
  app/app.js
  app/package-lock.json
  app/package.json
  app/src/routes/v1/permission.js
  app/src/routes/v1/user.js
  app/src/validators/common.js
  app/src/validators/index.js
  app/src/validators/permission.js
  app/src/validators/user.js
  app/tests/common/helper.js
  app/tests/unit/routes/v1/user.spec.js
  app/tests/unit/validators/common.spec.js
  app/tests/unit/validators/permission.spec.js
  app/tests/unit/validators/user.spec.js
Labels: enhancement, dependencies

#37 Versions
  app/src/controllers/object.js
  app/src/db/migrations/20220516000000_001-version.js
  app/src/db/models/index.js
  app/src/db/models/tables/objectModel.js
  app/src/db/models/tables/version.js
  app/src/docs/v1.api-spec.yaml
  app/src/services/index.js
  app/src/services/object.js
  app/src/services/storage.js
  app/src/services/version.js
Labels: documentation, enhancement

#41 Add Helm Chart support for COMS
  .github/workflows/charts-release.yaml
  .gitignore
  charts/coms/.helmignore
  charts/coms/Chart.yaml
  charts/coms/templates/NOTES.txt
  charts/coms/templates/_helpers.tpl
  charts/coms/templates/configmap.yaml
  charts/coms/templates/deploymentconfig.yaml
  charts/coms/templates/hpa.yaml
  charts/coms/templates/networkpolicy.yaml
  charts/coms/templates/route.yaml
  charts/coms/templates/secret.yaml
  charts/coms/templates/service.yaml
  charts/coms/templates/serviceaccount.yaml
  charts/coms/values.yaml
  openshift/app.bc.yaml
  openshift/app.dc.yaml
Labels: enhancement

#45 Release COMS v0.2.0
  SECURITY.md
  app/Dockerfile
  app/jest.config.js
  app/package-lock.json
  app/package.json
  charts/coms/Chart.yaml
Labels: bug, dependencies
