Repository bcgov/common-object-management-service, pull requests merged in 2022-09, with the labels that each got.

#70 Bugfix documentation incorrectly requiring keycloak serverUrl and realm
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1/docs.js
Labels: bug

#72 Routine supply-chain updates and v0.3.0 release chores
  README.md
  SECURITY.md
  app/README.md
  app/package-lock.json
  app/package.json
Labels: documentation, dependencies

#75 Postman collection for endpoints up to v.0.3
  app/src/docs/Common Object Management Service (COMS).postman_collection.json
Labels: documentation
