Repository bcgov/common-object-management-service, pull requests merged in 2023-10, with the labels that each got.

#217 RFC 7807 Compliance
  app/app.js
  app/package-lock.json
  app/package.json
  app/src/components/errorToProblem.js
  app/src/components/utils.js
  app/src/controllers/bucket.js
  app/src/controllers/object.js
  app/src/docs/v1.api-spec.yaml
  app/src/middleware/authentication.js
  app/src/middleware/authorization.js
  app/src/middleware/featureToggle.js
  app/src/middleware/upload.js
  app/src/middleware/validation.js
  app/src/routes/v1/object.js
  app/src/services/storage.js
  app/src/validators/bucket.js
  app/src/validators/bucketPermission.js
  app/src/validators/common.js
  app/src/validators/metadata.js
  app/src/validators/object.js
  app/src/validators/objectPermission.js
  app/src/validators/tag.js
  app/src/validators/user.js
  app/src/validators/version.js
  app/tests/common/helper.js
  app/tests/unit/components/errorToProblem.spec.js
  app/tests/unit/controllers/bucket.spec.js
  app/tests/unit/controllers/object.spec.js
  app/tests/unit/controllers/objectPermission.spec.js
  app/tests/unit/middleware/authentication.spec.js
  app/tests/unit/middleware/authorization.spec.js
  app/tests/unit/middleware/featureToggle.spec.js
  app/tests/unit/middleware/upload.spec.js
  app/tests/unit/middleware/validation.spec.js
  app/tests/unit/validators/object.spec.js
Labels: bug, documentation, enhancement, dependencies

#216 Remove request timeouts for upload endpoints
  .github/CODEOWNERS
  app/src/middleware/upload.js
  app/tests/unit/middleware/upload.spec.js
Labels: bug

#219 Remove Metadata length constraint and update dependencies
  Dockerfile
  app/package-lock.json
  app/package.json
  app/src/components/utils.js
  app/src/db/migrations/20231010000000_011-metadata-text.js
  app/src/db/models/tables/metadata.js
  app/src/docs/v1.api-spec.yaml
  app/src/validators/common.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/validators/common.spec.js
  app/tests/unit/validators/object.spec.js
Labels: bug, documentation, dependencies

#218 Release COMS v0.7.0
  SECURITY.md
  app/package-lock.json
  app/package.json
  charts/coms/Chart.yaml
  charts/coms/README.md
Labels: enhancement, dependencies

#223 Return back to alpine node base image
  Dockerfile
Labels: enhancement, dependencies
