Repository bcgov/common-object-management-service, pull requests merged in 2023-07, with the labels that each got.

#186 Remove multiplicity from createObject
  app/package-lock.json
  app/package.json
  app/src/components/constants.js
  app/src/controllers/object.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1/object.js
  app/src/services/storage.js
  app/src/validators/object.js
  app/tests/unit/routes/v1/object.spec.js
  app/tests/unit/services/storage.spec.js
  app/tests/unit/validators/object.spec.js
Labels: bug, documentation, enhancement, dependencies

#185 Update Authentication approach and jsonwebtoken dependency
  app/package-lock.json
  app/package.json
  app/src/components/keycloak.js
  app/src/middleware/authentication.js
  app/tests/unit/middleware/authentication.spec.js
Labels: bug, dependencies

#190 Implement synchronization endpoints
  app/src/controllers/index.js
  app/src/controllers/sync.js
  app/src/db/models/tables/objectModel.js
  app/src/db/models/tables/objectQueue.js
  app/src/routes/v1/bucket.js
  app/src/routes/v1/index.js
  app/src/routes/v1/object.js
  app/src/routes/v1/sync.js
  app/src/services/storage.js
  app/src/validators/bucket.js
  app/src/validators/index.js
  app/src/validators/object.js
  app/src/validators/sync.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/controllers/object.spec.js
  app/tests/unit/routes/v1.spec.js
  app/tests/unit/services/objectQueue.spec.js
  app/tests/unit/validators/bucket.spec.js
  app/tests/unit/validators/object.spec.js
  app/tests/unit/validators/sync.spec.js
Labels: bug, enhancement
